version: '3.4'

services:
  sirpolr3charter:
    image: ${DOCKER_REGISTRY-}sirpolr3charter
    build:
      context: .
      dockerfile: SirpoLR3Charter/Dockerfile
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: chartersDb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - 5440:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
 postgres-data:
